/**
 * Stimulus controllers index
 *
 * This file registers all Stimulus controllers for the application.
 * In a Rails app, this is typically auto-generated by stimulus:manifest:update.
 */

import { Application } from '@hotwired/stimulus';
import BookmarksWebmcpController from './bookmarks_webmcp_controller';

const application = Application.start();

// Configure Stimulus development experience
application.debug = false;
(window as unknown as { Stimulus: Application }).Stimulus = application;

// Register controllers
application.register('bookmarks-webmcp', BookmarksWebmcpController);

export { application };
